# -*- coding: utf-8 -*-
"""Aditya'sIntelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GoqwFW-wTGS9Aw8UZPBjw8y8FBbR557D
"""

!pip install opencv-python matplotlib transformers torch torchvision pillow

import cv2
import random
import torch
import matplotlib.pyplot as plt
from PIL import Image
from transformers import pipeline

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

emotion_classifier = pipeline(
    "image-classification",
    model="trpakov/vit-face-expression",
    device=-1
)

print("Select Gender:")
print("1️⃣ Male")
print("2️⃣ Female")

choice = input("Enter 1 or 2: ")

if choice == "1":
    gender = "male"
elif choice == "2":
    gender = "female"
else:
    raise ValueError("Invalid choice")

print(f"\n✅ Gender selected: {gender.upper()}")

from google.colab import files

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

img = cv2.imread(image_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.3,
    minNeighbors=5
)

if len(faces) == 0:
    print("❌ No face detected")
else:
    print(f"✅ {len(faces)} face(s) detected")

for (x, y, w, h) in faces:
    cv2.rectangle(
        img,
        (x, y),
        (x + w, y + h),
        (0, 0, 180),
        20
    )

plt.figure(figsize=(6,6))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis("off")

male_roasts = [
     """Aankhon mein confidence, chehre pe glow hai,
Lagta hai bhai ka selfie game next-level pro hai.""",

    """Hero wali entry, villain wali smile,
Bhai ka swag dekh ke camera bhi bole – ‘Once more bhai!’""",

    """Na filter ki zarurat, na angle ka jhol,
Bhai ka face card bole – full paisa vasool.""",

    """Mirror bhi bole aaj thoda sambhal ke reh,
Itna handsome dekh ke crack na ho jaaye kahin yeh.""",

    """Style aisa jaise movie ka scene ho,
Par acting nahi – bhai naturally machine ho.""",

    """Chehra bole ‘simple hoon’, attitude bole ‘king’,
Bhai ho toh aisa ho, full on main character thing."""
]


female_roasts = [
    """Smile aisi ki Wi-Fi bhi connect ho jaaye,
Camera dekhe aur bole – ‘Bas yahin ruk jaaye!’""",

    """Na filter, na makeup ka heavy saaj,
Natural beauty ho toh aisi ho, full on class.""",

    """Aankhon mein sparkle, chehre pe grace,
Lagta hai Insta bhi bole – ‘Reel bana le please.’""",



    """Soft si smile, thoda sa swag,
Cute aur cool ka perfect tag.""",

    """Beauty aisi ki joke bhi serious ho jaaye,
Aur dekhne wala bole – ‘Yaar, yeh toh alag hi vibe laaye.’"""
]

emotion_compliments = {
    "happy": [
        "Tumhari smile pure room ko light kar deti hai."
    ],
    "sad": [
        "Soft emotions bhi strength hote hain."
    ],
    "angry": [
        "Intensity powerful hai — leader vibes."
    ],
    "surprise": [
        "Expression bilkul natural aur lively hai."
    ],
    "fear": [
        "Even nervous moments mein bhi tum composed lagte ho."
    ],
    "neutral": [
        """Chehra seedha-saadha sa lagta hai,
Par isi saadgi mein sab kuch dikhta hai."""
    ],
    "disgust": [
        "Honest reactions hi sabse authentic hote hain."
    ]
}

x, y, w, h = faces[0]
face_img = img[y:y+h, x:x+w]
face_pil = Image.fromarray(cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB))

emotion_result = emotion_classifier(face_pil)
emotion = emotion_result[0]["label"].lower()

print(f"\n🎭 Detected Emotion: {emotion.upper()}")

def generate_roast(gender):
    if gender == "male":
        return random.choice(male_roasts)
    elif gender == "female":
        return random.choice(female_roasts)
    else:
        return "You look amazing!"

if len(faces) > 0:
    roast = generate_roast(gender)
    print("\n🔥COMPLIMENT ME AI SAYS 🔥\n")
    print(roast)

print("\n🔥 COMPLIMENT ME AI SAYS 🔥\n")

emotion_based = random.choice(
    emotion_compliments.get(emotion, ["You look great."])
)

print(emotion_based)





